services:
  db:
    image: postgres:16-alpine
    container_name: beautyconnect-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: beautyconnect
      POSTGRES_USER: beautyconnect
      POSTGRES_PASSWORD: beautyconnect
    ports:
      - "5433:5432"
    volumes:
      - beautyconnect-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beautyconnect"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Faux serveur mail pour intercepter les emails en local
  mailpit:
    image: axllent/mailpit
    container_name: beautyconnect-mail
    restart: unless-stopped
    ports:
      - "1025:1025" # Port utilisé par Spring Boot pour envoyer le mail
      - "8025:8025" # Port pour voir la boîte de réception dans ton navigateur

volumes:
  beautyconnect-db-data: