-- Base neuve : schéma complet. Base existante Hibernate : conserver les tables/données.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255),
    role VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS professional_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    business_name VARCHAR(255) NOT NULL, bio VARCHAR(2000), city VARCHAR(255) NOT NULL,
    address VARCHAR(255), profile_photo_url VARCHAR(255), target_gender VARCHAR(255) NOT NULL,
    validated BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS prestations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, professional_id BIGINT NOT NULL REFERENCES professional_profiles(id),
    name VARCHAR(255) NOT NULL, description VARCHAR(1000), type VARCHAR(255) NOT NULL,
    price NUMERIC(8,2) NOT NULL, duration_minutes INTEGER NOT NULL, active BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, professional_id BIGINT NOT NULL REFERENCES professional_profiles(id),
    start_date_time TIMESTAMP NOT NULL, available BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id BIGINT NOT NULL REFERENCES users(id),
    professional_id BIGINT NOT NULL REFERENCES professional_profiles(id), prestation_id BIGINT NOT NULL REFERENCES prestations(id),
    time_slot_id BIGINT NOT NULL REFERENCES time_slots(id), status VARCHAR(255) NOT NULL,
    notes VARCHAR(1000), created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id BIGINT NOT NULL REFERENCES users(id),
    professional_id BIGINT NOT NULL REFERENCES professional_profiles(id), appointment_id BIGINT REFERENCES appointments(id),
    rating INTEGER NOT NULL, comment VARCHAR(1000), hidden BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, reporter_id BIGINT NOT NULL REFERENCES users(id),
    target_type VARCHAR(255) NOT NULL, target_id BIGINT NOT NULL, reason VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    token VARCHAR(255) NOT NULL UNIQUE, expiry_date TIMESTAMP NOT NULL
);
